spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: on
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true


